version: '3'

services:
  nginx:
    image: nginx
    env_file:
      - .env
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./hleb:/hleb
      - ./log:/log
    ports:
      - '${SERVER_EXTERNAL_PORT}:80'

  php:
    environment:
      PHP_IDE_CONFIG: 'serverName=toaster'
    build: ./docker
    env_file:
      - .env
    volumes:
      - ./hleb:/hleb
      - ./log:/log
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro

  db:
    image: mariadb
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 'ok'
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - '${DATABASE_EXTERNAL_PORT}:3306'

  bot-poller:
    build: ./docker # Uses the same Dockerfile and context as the php service
    env_file:
      - .env
    volumes:
      - ./hleb:/hleb # Access to the hleb console script and application code
      - ./log:/log   # For any logs the command might produce directly
    command: ["sh", "-c", "composer dump-autoload -o -d /hleb/ && echo '--- HLEB COMMANDS LIST ---' && php /hleb/console --list"]
    restart: unless-stopped
    depends_on:
      php:
        condition: service_started # Ensures composer install & Hleb init in php service potentially runs first
      db:
        condition: service_started # If your command/app needs DB on startup
